[package]
name = "gres"
description = "Postgresql client library"
version = "0.1.0"
authors = ["J. Cliff Dyer <cdyer@edx.org>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2"
log = "0.4.11"
pretty_env_logger = "0.4"
gres-protocol = { path = "gres-protocol"}